name: Docker Image CI

env:
  BRANCH: GITHUB_REF##*/

on:
  push:
    branches: 
      - "8.2"
      - "8.3"
  pull_request:
    branches:
      - "main"
  # schedule:
  #   # At 02:00 on first day-of-each month
  #   - cron: "0 2 1 * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build image
      id: build
      uses: redhat-actions/buildah-build@v2.12
      with:
        containerfiles: |
          ./Containerfile
        image: ${{ github.repository }}
        tags: ${{ env.BRANCH }}
        # labels: # optional

    - name: Push To GHCR
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build.outputs.image }}
        tags: ${{ steps.build.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
